Section A - Question 1: List Operations

In [1]:
lst = [1, 2, 3, 4, 5]

lst.append(6)
print("Append:", lst)

lst.extend([7, 8])
print("Extend:", lst)

lst.insert(1, 10)
print("Insert:", lst)

lst.remove(10)
print("Remove:", lst)

lst.pop()
print("Pop:", lst)

print("Index of 3:", lst.index(3))
print("Count of 2:", lst.count(2))

lst.sort()
print("Sort:", lst)

lst.reverse()
print("Reverse:", lst)

lst.clear()
print("Clear:", lst)

Append: [1, 2, 3, 4, 5, 6]
Extend: [1, 2, 3, 4, 5, 6, 7, 8]
Insert: [1, 10, 2, 3, 4, 5, 6, 7, 8]
Remove: [1, 2, 3, 4, 5, 6, 7, 8]
Pop: [1, 2, 3, 4, 5, 6, 7]
Index of 3: 2
Count of 2: 1
Sort: [1, 2, 3, 4, 5, 6, 7]
Reverse: [7, 6, 5, 4, 3, 2, 1]
Clear: []


Question 2 (Tuple)

In [2]:
tup = ("Alice", "Bob", "Charlie")

# tup[1] = "David"  # This will give error
print("Tuple:", tup)

print("Explanation: Tuples are immutable, so values cannot be changed.")

Tuple: ('Alice', 'Bob', 'Charlie')
Explanation: Tuples are immutable, so values cannot be changed.


Question 3 (Set)

In [3]:
s = {1, 2, 2, 3, 4, 4}
print("Set:", s)

print("Explanation: Duplicate values are automatically removed in sets.")

Set: {1, 2, 3, 4}
Explanation: Duplicate values are automatically removed in sets.


Question 4 (Dictionary)

In [4]:
d = {'name': 'John', 'age': 20, 'city': 'Hyderabad'}

d['age'] = 21
d['email'] = 'john@gmail.com'

print("Updated Dictionary:", d)

Updated Dictionary: {'name': 'John', 'age': 21, 'city': 'Hyderabad', 'email': 'john@gmail.com'}


Question 5 (Voting)

In [5]:
age = int(input("Enter age: "))

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter age: 17
Not eligible to vote


Question 6 (Grades)

In [6]:
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

Enter marks: 89
Grade B


Question 7 (Positive & Even)

In [7]:
num = int(input("Enter number: "))

if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Enter number: 9
Positive but Odd


##Section B: NumPy

In [8]:
import numpy as np

In [9]:
# Scalar
a = np.array(5)
print("Scalar:", a)

# 1D array
b = np.array([1, 2, 3, 4, 5])
print("1D Array:", b)

# 2D array
c = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", c)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


random array

In [10]:
rand_arr = np.random.randint(0, 100, (4, 4))
print("Random Array:\n", rand_arr)

Random Array:
 [[78 86 51 90]
 [14 91 53 51]
 [91 47 86 90]
 [ 2 15 71 66]]


Convert to DataFrame

In [11]:
import pandas as pd

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr, columns=['A','B','C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


###Section C: Pandas

Create DataFrame

In [12]:
data = {
    'Name': ['A','B','C','D','E','F','G','H','I','J'],
    'Age': [20,21,22,23,24,25,26,27,28,29],
    'City': ['Hyd','Del','Mum','Chn','Hyd','Del','Mum','Chn','Hyd','Del'],
    'Salary': [20000,25000,None,30000,35000,None,40000,45000,50000,55000]
}

df = pd.DataFrame(data)
print(df)

  Name  Age City   Salary
0    A   20  Hyd  20000.0
1    B   21  Del  25000.0
2    C   22  Mum      NaN
3    D   23  Chn  30000.0
4    E   24  Hyd  35000.0
5    F   25  Del      NaN
6    G   26  Mum  40000.0
7    H   27  Chn  45000.0
8    I   28  Hyd  50000.0
9    J   29  Del  55000.0


Operations

In [13]:
print(df.info())
print(df.describe())

print(df[['Name','City']])

df = df.drop(columns=['City'])

df['Salary'].fillna(df['Salary'].mean(), inplace=True)

df = df.drop_duplicates()

print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
            Age        Salary
count  10.00000      8.000000
mean   24.50000  37500.000000
std     3.02765  12247.448714
min    20.00000  20000.000000
25%    22.25000  28750.000000
50%    24.50000  37500.000000
75%    26.75000  46250.000000
max    29.00000  55000.000000
  Name City
0    A  Hyd
1    B  Del
2    C  Mum
3    D  Chn
4    E  Hyd
5    F  Del
6    G  Mum
7    H  Chn
8    I  Hyd
9    J  Del
  Name  Age   Salary
0    A   20  20000.0
1    B   21  25000.0
2    C   22  37500.0
3    D   23  30000.0
4    E   24  35000.0
5    F   25  37500.0
6    G   26  40000.0
7    H   27  45000.0
8    I   28  5

/tmp/ipykernel_17142/555623833.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
